services:
  app:
    depends_on:
      postgres:
        condition: service_healthy
    # TODO: replace with the GHCR image you pushed
    # (e.g. ghcr.io/<your-username>/docuseal:latest)
    image: docuseal/docuseal:latest
    ports:
      - 3000:3000
    volumes:
      - ./docuseal:/data/docuseal
    environment:
      - FORCE_SSL=${HOST}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/docuseal
    networks:
      - docuseal_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docuseal.rule=Host(`${HOST}`)" 
      - "traefik.http.routers.docuseal.entrypoints=websecure"
      - "traefik.http.routers.docuseal.tls.certresolver=letsencrypt"
      - "traefik.http.services.docuseal.loadbalancer.server.port=3000"

  postgres:
    image: postgres:18
    volumes:
      - './pg_data:/var/lib/postgresql/18/docker'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: docuseal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - docuseal_net

  traefik:
    image: traefik::3.6.15
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - docuseal_net

networks:
  docuseal_net:
    name: docuseal_net
    external: false