name: Provision Infrastructure
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      # TODO: Add the steps to provision a Hetzner server and 
      # configure it via Terraform and Ansible

 